"""Add token and token_expiration

Revision ID: 0d6d2e400eb1
Revises: a190ff5fd761
Create Date: 2022-09-01 11:23:33.365479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6d2e400eb1'
down_revision = 'a190ff5fd761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('toekn_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'toekn_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
