"""empty message

Revision ID: ffec67cba5f2
Revises: 0d6d2e400eb1
Create Date: 2022-09-01 11:25:57.607509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffec67cba5f2'
down_revision = '0d6d2e400eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.drop_column('user', 'toekn_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('toekn_expiration', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###
